# Generated by Django 2.2.8 on 2020-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='documents/')),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
